Migration to jazzy docs
bitstadium/HockeySDK-tvOS pull request #17
Opened 2017-07-14 10:08 UTC by bmourat

2017-07-14 10:08 UTC, msftclas commented
@bmourat,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-14 10:29 UTC, msftclas commented
@bmourat,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-14 14:47 UTC, msftclas commented
@bmourat,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-15 00:59 UTC, TroubleMakerBen commented
Hey Murat,

Could you please go ahead and fix the paths to generate a valid Docset, [like Ivan did for the iOS SDK](https://github.com/bitstadium/HockeySDK-iOS/pull/436/commits) and please use objc/swift for the code blocks in the docs? Thx!

Benny

2017-07-15 01:00 UTC, ElektrojungeAtWork requested changes
As commented.

2017-07-17 10:40 UTC, bmourat commented
Hey Benny,
May be i'am missing something but all paths seem to be similar to the ones in iOS version, and i'am using objc/swift for the code blocks.

2017-07-18 20:18 UTC, ElektrojungeAtWork approved these changes

2017-07-18 20:20 UTC, ElektrojungeAtWork approved these changes

2017-07-18 20:57 UTC, merged